.TH "_SHA512_CTX" 3 "Fri Oct 4 2019" "Version 1" "libfortuna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SHA512_CTX
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sha2\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u_int64_t \fBstate\fP [8]"
.br
.ti -1c
.RI "u_int64_t \fBbitcount\fP [2]"
.br
.ti -1c
.RI "u_int8_t \fBbuffer\fP [\fBSHA512_BLOCK_LENGTH\fP]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "u_int64_t _SHA512_CTX::bitcount[2]"

.SS "u_int8_t _SHA512_CTX::buffer[\fBSHA512_BLOCK_LENGTH\fP]"

.SS "u_int64_t _SHA512_CTX::state[8]"


.SH "Author"
.PP 
Generated automatically by Doxygen for libfortuna from the source code\&.
