.TH "fortuna.h" 3 "Fri Oct 4 2019" "Version 1" "libfortuna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fortuna.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfortuna_get_bytes\fP (unsigned len, unsigned char *dst)"
.br
.ti -1c
.RI "void \fBfortuna_add_entropy\fP (const unsigned char *data, unsigned len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void fortuna_add_entropy (const unsigned char * data, unsigned len)"

.SS "void fortuna_get_bytes (unsigned len, unsigned char * dst)"

.SH "Author"
.PP 
Generated automatically by Doxygen for libfortuna from the source code\&.
