.TH "fortuna.c" 3 "Fri Oct 4 2019" "Version 1" "libfortuna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fortuna.c
.SH SYNOPSIS
.br
.PP
\fC#include <sys/time\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'rijndael\&.h'\fP
.br
\fC#include 'sha2\&.h'\fP
.br
\fC#include 'fortuna\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBfortuna_state\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNUM_POOLS\fP   23"
.br
.ti -1c
.RI "#define \fBRESEED_INTERVAL\fP   100000	/* 0\&.1 sec */"
.br
.ti -1c
.RI "#define \fBRESEED_BYTES\fP   (1024*1024)"
.br
.ti -1c
.RI "#define \fBPOOL0_FILL\fP   (256/8)"
.br
.ti -1c
.RI "#define \fBBLOCK\fP   32"
.br
.ti -1c
.RI "#define \fBCIPH_BLOCK\fP   16"
.br
.ti -1c
.RI "#define \fBMD_CTX\fP   \fBSHA256_CTX\fP"
.br
.ti -1c
.RI "#define \fBCIPH_CTX\fP   \fBrijndael_ctx\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBfortuna_state\fP \fBFState\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfortuna_add_entropy\fP (const u_int8_t *data, unsigned len)"
.br
.ti -1c
.RI "void \fBfortuna_get_bytes\fP (unsigned len, u_int8_t *dst)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFState\fP \fBmain_state\fP"
.br
.ti -1c
.RI "int \fBinit_done\fP = 0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BLOCK   32"

.SS "#define CIPH_BLOCK   16"

.SS "#define CIPH_CTX   \fBrijndael_ctx\fP"

.SS "#define MD_CTX   \fBSHA256_CTX\fP"

.SS "#define NUM_POOLS   23"

.SS "#define POOL0_FILL   (256/8)"

.SS "#define RESEED_BYTES   (1024*1024)"

.SS "#define RESEED_INTERVAL   100000	/* 0\&.1 sec */"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBfortuna_state\fP \fBFState\fP"

.SH "Function Documentation"
.PP 
.SS "void fortuna_add_entropy (const u_int8_t * data, unsigned len)"

.SS "void fortuna_get_bytes (unsigned len, u_int8_t * dst)"

.SH "Variable Documentation"
.PP 
.SS "int init_done = 0"

.SS "\fBFState\fP main_state"

.SH "Author"
.PP 
Generated automatically by Doxygen for libfortuna from the source code\&.
