.TH "random.c" 3 "Fri Oct 4 2019" "Version 1" "libfortuna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
random.c
.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'random\&.h'\fP
.br
\fC#include 'fortuna\&.h'\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRND_BYTES\fP   32"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBget_pseudo_random_bytes\fP (u_int8_t *dst, unsigned count)"
.br
.ti -1c
.RI "int \fBadd_entropy\fP (const u_int8_t *data, unsigned count)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RND_BYTES   32"

.SH "Function Documentation"
.PP 
.SS "int add_entropy (const u_int8_t * data, unsigned count)"

.SS "int get_pseudo_random_bytes (u_int8_t * dst, unsigned count)"

.SH "Author"
.PP 
Generated automatically by Doxygen for libfortuna from the source code\&.
